### ISSUE TITLE
Can't init a project

### ISSUE THREAD

**Issue by diberry** [aaronpowell/create-swa-app#1]
- On Windows 11 internal
- Node 14.17.1
- Npm 6.14.13
- bash prompt
- Command: npm init @aaronpowell/swa-app my-swa-app
- Issue: I think the double C:\C:\ is an issue. 
- Error: Error: ENOENT: no such file or directory, open 'C:\C:\Users\diberry\AppData\Roaming\npm-cache\_npx\2376\node_modules\@aaronpowell\create-swa-app\templates.json'

![image](https://user-images.githubusercontent.com/41597107/145885324-6b1aa55f-fd4a-471d-903c-8834aa1333dd.png)

Verbose mode shows:

```
$ npm init @aaronpowell/swa-app my-swa-app --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'init',
npm verb cli   '@aaronpowell/swa-app',
npm verb cli   'my-swa-app',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.13
npm info using node@v14.17.1
npx: installed 140 in 20.23so using node@v14.17.1
✨ Welcome to the Azure Static Web App generator ✨
Let's get started scaffolding you an app
Error: ENOENT: no such file or directory, open 'C:\C:\Users\diberry\AppData\Roaming\npm-cache\_npx\2376\node_modules\@aaronpowell\create-swa-app\templates.json'
npm verb exit [ 0, true ]
npm timing npm Completed in 21324ms
npm info ok
```

**Comment by aaronpowell** [comment]
Thanks @diberry, looked like a Windows specific issue with how I was detecting the current folder. Fixed this with https://github.com/aaronpowell/create-swa-app/releases/tag/v1.0.4
